name: Issue assignment

on:
    issue_comment:
        types: [created]
jobs:
    find-comment:
        name: Find Comment
        if: ${{ !github.event.issue.pull_request }}
        runs-on: ubuntu-latest 
        steps:
          - uses: actions/checkout@v3
          - name: finds the comment
            uses: peter-evans/find-comment@v2
            id: fc
            with:
                issue-number: ${{github.event.issue.number}}
                body-includes: assign
        outputs:
            author: ${{ steps.fc.outputs.comment-author}}
          
    auto-assign:  
        name: assign the issue
        needs: find-comment
        if: ${{ !github.event.issue.pull_request }}
        runs-on: ubuntu-latest
        steps: 
          - uses: actions/checkout@v3
          - name: 'Auto-assign issue'
            uses: pozil/auto-assign-issue@v1
            with:
                assignees: ${{needs.find-comment.outputs.author}}
                numOfAssignee: 1
                allowSelfAssign: true

    message-assignee:
        name: replies with message
        needs: [auto-assign, find-comment]
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: 'Comment on issue'
            uses: ben-z/actions-comment-on-issue@1.0.2
            with:
                message: "Assigned issue to ${{ needs.find-comment.outputs.author}}"
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
